# https://hub.docker.com/r/library/node/tags/
image: node:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#AWS access keys stored as secret variables 
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

before_script:
  - npm install
#This declares the pipeline stages  
stages:
  - test
  - build
  - deploy
cache:
  paths:
  - node_modules/
build:
  stage: build
  script:
    - npm run-script build
test:
  stage: test
  script:
    - echo "Running react test suite......"
deployToAWS:
  stage: deploy
  script:
    - install python3-pip
    - pip3 install awscli --upgrade --user
    - npm run-script deploy