image: nikolaik/python-nodejs:latest
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
cache:
  paths:
    - node_modules/
stages:
  - test
  - build
  - deploy
test:
  stage: test
  script:
    - npm i -g pm2
    - npm i
    - pm2 start npm -- start 
    - npm test
build:
  stage: build
  script:
    - npm run build
  artifacts: 
    paths: 
    - ./build/
deploy:
  stage: deploy
  script:
    - pip install awscli
    - aws s3 cp ./build/ s3://order-manager-mc --recursive --include "*"
