version: 2
jobs:
  npm-install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "installing npm"
      - run: npm i
      - run: echo "installed completed"
workflows:
  version: 2
  production:
    jobs:
      - npm-install
