version: 2
jobs:
  npm-install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "installing npm"
      - run: npm i
      - run: sudo npm i -g wait-on
      - run: echo "installed completed"
      - run: echo "starting npm server"
      - run: npm start wait-on http://localhost:3000
workflows:
  version: 2
  production:
    jobs:
      - npm-install
