version: 2
jobs:
  npm-install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "installing npm"
      - run: npm i
      - run: echo "installed completed"
      - store_artifacts:
        path: node_modules/
  npm-start:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "starting npm server"
workflows:
  version: 2
  production:
    jobs:
      - npm-install
      - npm-start 
