version: 2
jobs:
  npm-install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "installing npm"
      - run: npm i
      - run: sudo npm i -g wait-on
      - run: echo "installed completed"
      - run: echo "starting npm server"
      - run: 
          command: npm start
          background: true
      - save_cache:
          key: my-cache
          paths:
            - node_modules
  npm-test:
    docker:
      - image: selenium:standalone-chrome
    steps:
      - checkout 
      - run: echo "starting test"
workflows:
  version: 2
  production:
    jobs:
      - npm-install